### PR TITLE
Added to installation and use instructions in README

### PR DESCRIPTION
**Pull request by smlum**
Added link for the .xpi file

### CODE REVIEW

**Comment by eschnett** [comment]
Thanks!

I have a request. As is, this url needs to be updated for every new release. Would it makes sense to update the url to `https://github.com/eschnett/zotero-citationcounts/releases/download`, and state that one should download the latest `xpi` file from there?

**Comment by smlum** [comment]
Sweet yes that's a better idea! Requires less maintenance.
If going down that route it might also be worth adding something like - "to download the .xpi file right click it and select 'Save link as' " - (since the default behaviour on Firefox is to try and install it as an extension)

**Comment by smlum** [comment]
Updated in last commit - hopefully helpful to others finding this plugin!

**Comment by eschnett** [comment]
Thanks!

**Pull request merged**
